#goal definition
int32 g_base
int32 g_shoulder
int32 g_elbow
int32 g_wrist
int32 g_gripper
int32 g_wristRotate
int32 g_time

---
#result definition
int32 r_finalPose

---
#feedback
int32 f_procesStatus