@startuml behavioral state machine
title behavioral state machine robot arm
[*] --> STAND_BY
STAND_BY --> MOVING : gotoPosition(goalPosition) == valid
MOVING --> STAND_BY : goalPosition == position
MOVING --> STAND_BY : emergencyStop
@enduml