@startuml behavioral state machine
title behavioral state machine robot arm
[*] --> NOT_MOVING
NOT_MOVING --> MOVING : gotoPosition [goalPosition = valid]
MOVING --> NOT_MOVING : done
MOVING --> NOT_MOVING : emergencyStop emptyQueue/
@enduml