@startuml Compnent diagram


package "robot_arm" <<system>>  {
    node "High Level Driver" <<sub system>> {
        [MessageHandler] 

        [AL5D] -UP-> gotoPosition
        [AL5D] -UP-> stopAllMotorFunctions
        [AL5D] -UP-> isAtDestination
        [AL5D] --> getCurrentPosition

        [AL5D] -LEFT-( move

        [MessageHandler] --( gotoPosition
        [MessageHandler] --( stopAllMotorFunctions
        [MessageHandler] --( isAtDestination
    }
    node "Low Level Driver" <<sub system>> {    
        [SSC32U]
    }
    [SSC32U] -> move 
    [SSC32U] --> setPositionOffset 
}

[MessageHandler] -UP-> handleInstruction 

package "robot_arm_controller" <<system>>  {

[InputController] --( handleInstruction

@enduml