@startuml Compnent diagram

title Component diagram AL5D robot arm controller

package "robot_arm" <<system>>  {
    node "High Level Driver" <<sub system>> {
        [MessageHandler] 

        [AL5D] -up-> gotoPosition
        [AL5D] -up-> stopAllMotorFunctions
        [AL5D] -up-> isAtDestination
        [AL5D] -> getCurrentPosition

        [AL5D] -LEFT-( move

        [MessageHandler] --( gotoPosition
        [MessageHandler] --( stopAllMotorFunctions
        [MessageHandler] --( isAtDestination
    }
    node "Low Level Driver" <<sub system>> {    
        [SSC32U]
    }
    [SSC32U] -left-> move 
    [SSC32U] -up-> setPositionOffset 
}

' [MessageHandler] -UP-> handleInstruction 
' [MessageHandler] #-UP-> robot_arm 
' robot_arm #-- 

package "robot_arm_controller" <<system>>  {
    [InputController]
}

[InputController] --# robot_arm_controller : ROS Action
[MessageHandler] --# robot_arm : ROS Action
robot_arm #-> handleInstruction : ROS Action
robot_arm_controller #--( handleInstruction : ROS Action
@enduml