@startuml

title Robot_arm{protocol}

state Robot_arm {

[*] -left-> Park_pose
Park_pose -down-> Moving : [armIsConnected()]/
Ready_pose -down-> Moving : [armIsConnected()]/
Straight_up_pose -down-> Moving : [armIsConnected()]/

Moving -left-> Standby : [armIsMoving()]/[armIsAtPos()]

Standby --> Park_pose : setPose-action/
Standby --> Ready_pose : setPose-action/
Standby --> Straight_up_pose : setPose-action/

Moving --> Emergency_stop : emergency-action/[queueIsEmpty() && !armIsMoving()]
Emergency_stop --> Standby

}

state Robot_arm_controller {
    [*] --> Getting_user_imput
    Getting_user_imput --> Create_message : [userIsPresentedWithInstructions()]userInputDone/[userInputIsValid()]
    Create_message -right-> Send_message : /[recieverNodeIsOnline()]
    Send_message --> Getting_user_imput : [MessageIsSend]/
}

@enduml